{% set name = "semi-ate-installer" %}
{% set version = "0.0.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 865e362ad4e2f457ad46b9032ce1db42a6a72d502397cb16839a6e55bd5af70d

build:
  entry_points:
    - semi-ate-installer = semi_ate_installer.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - hatchling
    - mamba =1.5.12
  run:
    - packaging
    - pyfiglet >=0.8
    - python >={{ python_min }}
    - questionary ==1.10.0
    - conda
    - mamba =1.5.12
    - hatchling
    - click

test:
  imports:
    - semi_ate_installer
  commands:
    - pip check
    - "semi-ate-installer --help"
  requires:
    - pip
    - hatchling
    #- mamba =1.5.12
    - python {{ python_min }}

about:
  home: https://github.com/Semi-ATE/Semi-ATE-Installer
  summary: Semi ATE Installer package for ATE Projects.
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
    - heli2src
    - Zlin526F
