{% set name = "semi-ate-installer" %}
{% set version = "0.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/semi-ate-installer-{{ version }}.tar.gz
  sha256: 55fc6f99dbd549107e130eec444f6510b52fc2335b691c182cbb7fa40d50fbc3

build:
  entry_points:
    - semi-ate-installer = semi_ate_installer.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
    - hatchling
    - mamba=1.5.12
  run:
    - packaging
    - pyfiglet >=0.8
    - python >=3.9
    - questionary ==1.10.0
    - conda
    - mamba=1.5.12
    - click

test:
  imports:
    - semi_ate_installer
  commands:
    - pip check
    - "semi-ate-installer --help"
  requires:
    - pip
    #- mamba=1.5.12

about:
  home: https://github.com/Semi-ATE/Semi-ATE-Installer
  summary: Semi ATE Installer package for ATE Projects.
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
    - heli2src
    - Zlin526F  
